//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CariKart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CariKart()
        {
            this.MusteriSiparisMaster = new HashSet<MusteriSiparisMaster>();
            this.MusteriTeklifMaster = new HashSet<MusteriTeklifMaster>();
            this.MusteriKampanyalari = new HashSet<MusteriKampanyalari>();
        }
    
        public int id { get; set; }
        public bool Aktif { get; set; }
        public string CariAdi { get; set; }
        public string TeslimatAdi { get; set; }
        public string KisaAdi { get; set; }
        public string KartTipi { get; set; }
        public string Sirket_Kod { get; set; }
        public string DovizKod { get; set; }
        public double Iskonto1 { get; set; }
        public double Iskonto2 { get; set; }
        public string YetkiliSicilNo { get; set; }
        public string YurtIciDisi { get; set; }
        public string VergiDairesi { get; set; }
        public long VergiNo { get; set; }
        public string FaturaAdresi { get; set; }
        public string FaturaPostaKodu { get; set; }
        public string FaturaIlceSemt { get; set; }
        public string FaturaIL { get; set; }
        public string FaturaUlke { get; set; }
        public string TeslimatAdresi { get; set; }
        public string TeslimatPostaKodu { get; set; }
        public string TeslimatIlceSemt { get; set; }
        public string TeslimatIL { get; set; }
        public string TeslimatUlke { get; set; }
        public string TeslimatKodu { get; set; }
        public string OdemeKodu { get; set; }
        public string Telefon1 { get; set; }
        public string Telefon2 { get; set; }
        public string Faks { get; set; }
        public string LojistikKontakKisi { get; set; }
        public string LojistikTel1 { get; set; }
        public string FaturaKontakKisi { get; set; }
        public string FaturaTel1 { get; set; }
        public string KontakKisi3 { get; set; }
        public string Kontak3Tel1 { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KullaniciKodu { get; set; }
        public Nullable<System.DateTime> DegisiklikTarihi { get; set; }
        public string DegKullaniciKodu { get; set; }
        public bool MusteriSiplerininSatSipleriniBirlestir { get; set; }
        public bool KampanyalariSatSiplerindeBirlestir { get; set; }
        public bool SatinalmaSiparisleriOnayliOlsun { get; set; }
        public bool SiparisteOlmayanlariTekliftenGetir { get; set; }
        public double BlokeOrani { get; set; }
        public bool SevkiyatlarPaletli { get; set; }
        public string FaturaSatirTipi { get; set; }
        public string CariOzelKodu { get; set; }
        public string Kisaltma { get; set; }
        public string FaturaEkBilgileri { get; set; }
        public string TeslimatUnvani { get; set; }
        public string FaturaMail2 { get; set; }
        public string FaturaMail3 { get; set; }
        public string FaturaMail4 { get; set; }
        public string FaturaMail5 { get; set; }
        public string FaturaMail6 { get; set; }
        public string SatisUlke1 { get; set; }
        public string SatisUlke2 { get; set; }
        public int TeklifGun { get; set; }
        public int StokGun { get; set; }
        public bool BarkodGonderilsin { get; set; }
        public bool Gumrukcu { get; set; }
        public string SiparisMail { get; set; }
        public string LojistikMail { get; set; }
        public string FaturaMail { get; set; }
        public string Kontak3Mail { get; set; }
        public int SiparisTipi { get; set; }
        public string EFaturaProfileIDType { get; set; }
        public string TICARETSICILNO { get; set; }
        public string MERSISNO { get; set; }
        public string SahisAdi1 { get; set; }
        public string SahisAdi2 { get; set; }
        public string SahisSoyadi { get; set; }
        public string Iban { get; set; }
        public string OdemeGunu { get; set; }
        public string MuhHesapKod { get; set; }
        public string WebKullaniciNo { get; set; }
        public string WebKullaniciSifre { get; set; }
        public string WebKullaniciRoles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriSiparisMaster> MusteriSiparisMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriTeklifMaster> MusteriTeklifMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriKampanyalari> MusteriKampanyalari { get; set; }
    }
}
