//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategoriler()
        {
            this.Kampanyalar = new HashSet<Kampanyalar>();
        }
    
        public int id { get; set; }
        public string Sirket_Kod { get; set; }
        public string Tanim { get; set; }
        public bool Aktif { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KullaniciKodu { get; set; }
        public Nullable<System.DateTime> DegisiklikTarihi { get; set; }
        public string DegKullaniciKodu { get; set; }
        public string TanimTR { get; set; }
        public string MuhHesapKodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kampanyalar> Kampanyalar { get; set; }
    }
}
