//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KonseptlerGecici
    {
        public int id { get; set; }
        public int Genelid { get; set; }
        public int Konseptid { get; set; }
        public string Tanim { get; set; }
        public bool Aktif { get; set; }
        public bool Secim { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    }
}
