//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTeklifDetayGecici
    {
        public int id { get; set; }
        public string Sirket_Kod { get; set; }
        public int Masterid { get; set; }
        public string SKUKodu { get; set; }
        public double BirTaneicinAlisFiyati { get; set; }
        public double ListeAlisFiyati { get; set; }
        public double SatisFiyati { get; set; }
        public double OzelFiyat { get; set; }
        public double Marj { get; set; }
        public double RetailFiyat { get; set; }
        public double Miktar { get; set; }
        public bool Iptal { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public string KullaniciKodu { get; set; }
        public Nullable<System.DateTime> DegisiklikTarihi { get; set; }
        public string DegKullaniciKodu { get; set; }
        public double TedarikciStogu { get; set; }
        public double AsirStok { get; set; }
        public double BlokeStok { get; set; }
        public double KalanStok { get; set; }
        public double VerilecekStok { get; set; }
        public double UyariMarj { get; set; }
        public int sipdetayid { get; set; }
    }
}
