//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriSiparisMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriSiparisMaster()
        {
            this.MusteriSiparisDetay = new HashSet<MusteriSiparisDetay>();
        }
    
        public int id { get; set; }
        public string Sirket_Kod { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
        public int Musteriid { get; set; }
        public int SiparisTipi { get; set; }
        public int Teklifid { get; set; }
        public int MKampanyaid { get; set; }
        public string MKampanyaKodu { get; set; }
        public string YurtIciDisi { get; set; }
        public string DovizKod { get; set; }
        public int Oncelik { get; set; }
        public bool DipIskYuzdelik { get; set; }
        public double DipIskYuzde { get; set; }
        public double DipIskTutar { get; set; }
        public bool VATyuzdelik { get; set; }
        public double VATyuzde { get; set; }
        public double VATtutar { get; set; }
        public double FreightTutar { get; set; }
        public double SatirIsk1 { get; set; }
        public double SatirIsk2 { get; set; }
        public bool Onay { get; set; }
        public Nullable<System.DateTime> OnayTarihi { get; set; }
        public int FaturaCariid { get; set; }
        public string FaturaCariKod { get; set; }
        public string FaturaCariAdi { get; set; }
        public string FaturaAdresi { get; set; }
        public string FaturaPostaKodu { get; set; }
        public string FaturaIlceSemt { get; set; }
        public string FaturaIL { get; set; }
        public string FaturaUlke { get; set; }
        public string TeslimatAdresi { get; set; }
        public string TeslimatPostaKodu { get; set; }
        public string TeslimatIlceSemt { get; set; }
        public string TeslimatIL { get; set; }
        public string TeslimatUlke { get; set; }
        public int TeslimatCariid { get; set; }
        public string TeslimatCariKod { get; set; }
        public string TeslimatCariAdi { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KullaniciKodu { get; set; }
        public Nullable<System.DateTime> DegisiklikTarihi { get; set; }
        public string DegKullaniciKodu { get; set; }
        public string Aciklama { get; set; }
        public bool ExcelGonderildi { get; set; }
        public bool PDFGonderildi { get; set; }
        public string ExcelMailAcik { get; set; }
        public string PDFMailAcik { get; set; }
        public string InvoiceNo { get; set; }
        public string SatisKodu { get; set; }
        public string SatisAdi { get; set; }
        public string EFaturaGonder { get; set; }
        public string SahisAdi1 { get; set; }
        public string SahisAdi2 { get; set; }
        public string SahisSoyadi { get; set; }
        public string CariAlias { get; set; }
        public string EFaturaDurumAciklamasi { get; set; }
        public string EFaturaZardUUID { get; set; }
        public string EFaturaAciklama { get; set; }
        public bool IrsaliyeYOK { get; set; }
        public Nullable<System.Guid> ETTNuuid { get; set; }
        public string ettnUUIDstr { get; set; }
        public string hk_IhracKaydi { get; set; }
        public string hk_VergiReasonCode { get; set; }
        public string SeriNo { get; set; }
        public string BelgeNo { get; set; }
        public string EFaturaProfileIDType { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string OdemeKodu { get; set; }
    
        public virtual CariKart CariKart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriSiparisDetay> MusteriSiparisDetay { get; set; }
    }
}
