//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriSiparisDetay
    {
        public int id { get; set; }
        public string Sirket_Kod { get; set; }
        public int Masterid { get; set; }
        public int TeklifDetayid { get; set; }
        public int TeklifMasterid { get; set; }
        public int Stokid { get; set; }
        public string SKUKodu { get; set; }
        public double Miktar { get; set; }
        public double Fiyat { get; set; }
        public double MalTutari { get; set; }
        public double Isk1 { get; set; }
        public double Isk2 { get; set; }
        public double TopIskTutari { get; set; }
        public bool KdvDahil { get; set; }
        public double KDVOrani { get; set; }
        public double KdvTutari { get; set; }
        public double AraToplam { get; set; }
        public double GenelToplam { get; set; }
        public bool Kapandi { get; set; }
        public string Aciklama { get; set; }
        public bool iptalEdildi { get; set; }
        public string iptalAciklama { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KullaniciKodu { get; set; }
        public Nullable<System.DateTime> DegisiklikTarihi { get; set; }
        public string DegKullaniciKodu { get; set; }
        public double SevkMiktari { get; set; }
        public Nullable<System.DateTime> SonSevkTarihi { get; set; }
        public double IptalMiktari { get; set; }
        public double IptalMiktari2 { get; set; }
        public double IadeMiktari { get; set; }
    
        public virtual MusteriSiparisMaster MusteriSiparisMaster { get; set; }
        public virtual StokKarti StokKarti { get; set; }
    }
}
