//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sabitler
    {
        public string ExcelDosyaYolu { get; set; }
        public string Marka { get; set; }
        public string UrunBarkodNo { get; set; }
        public string SKUKodu { get; set; }
        public string StokIsmi { get; set; }
        public string Renk { get; set; }
        public string StokAciklama { get; set; }
        public string Ozellik { get; set; }
        public string EkstraOzellik { get; set; }
        public string UreticiBarkodNo { get; set; }
        public string Aktif { get; set; }
        public string KampanyaDosyaIsmi { get; set; }
        public string Birim { get; set; }
        public int Genelid { get; set; }
        public string AlisFiyati { get; set; }
        public string DovizKodu { get; set; }
        public string Host { get; set; }
        public int Port { get; set; }
        public string Mailusername { get; set; }
        public string Mailpassword { get; set; }
        public double PuanKatsayi1 { get; set; }
        public double PuanKatsayi2 { get; set; }
        public double BirKoliUcreti { get; set; }
        public double BirPaletUcreti { get; set; }
        public double BirKoliM3 { get; set; }
        public double BirPaletM3 { get; set; }
        public double BirKoliKG { get; set; }
        public double BirPaletKG { get; set; }
        public double BirPaletForkliftUcreti { get; set; }
        public double OrtSevkSuresi { get; set; }
        public string En { get; set; }
        public string Boy { get; set; }
        public string Yukseklik { get; set; }
        public string Agirlik { get; set; }
        public string UreticiStokKodu { get; set; }
        public string StokBitincePasif { get; set; }
        public string KonseptTanim { get; set; }
        public int id { get; set; }
        public string GercekAlisFiyati { get; set; }
        public string FTPKucukResimYolu { get; set; }
    }
}
