//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirketler
    {
        public int id { get; set; }
        public string SirketKod { get; set; }
        public string Sirket_Kod { get; set; }
        public byte Sira { get; set; }
    }
}
