//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKarti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StokKarti()
        {
            this.MusteriSiparisDetay = new HashSet<MusteriSiparisDetay>();
        }
    
        public int id { get; set; }
        public string Sirket_Kod { get; set; }
        public string SKUKodu { get; set; }
        public string Marka { get; set; }
        public string Birim { get; set; }
        public string UreticiBarkodNo { get; set; }
        public string UrunBarkodNo { get; set; }
        public string StokIsmi { get; set; }
        public bool Aktif { get; set; }
        public string Ozellik { get; set; }
        public string EkstraOzellik { get; set; }
        public string Renk { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KullaniciKodu { get; set; }
        public byte[] KucukResim { get; set; }
        public int Kampanyaid { get; set; }
        public int Aciklamaid { get; set; }
        public Nullable<System.DateTime> DegisiklikTarihi { get; set; }
        public string DegKullaniciKodu { get; set; }
        public double AlisFiyati { get; set; }
        public string DovizKodu { get; set; }
        public double En { get; set; }
        public double Boy { get; set; }
        public double Yukseklik { get; set; }
        public double Agirlik { get; set; }
        public double Puan { get; set; }
        public string UreticiStokKodu { get; set; }
        public bool StokBitincePasif { get; set; }
        public string Beden { get; set; }
        public int Konseptid { get; set; }
        public double AktarMik { get; set; }
        public double KampanyaPuan { get; set; }
        public double GercekAlisFiyati { get; set; }
    
        public virtual Kampanyalar Kampanyalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriSiparisDetay> MusteriSiparisDetay { get; set; }
        public virtual StokKartiTanim StokKartiTanim { get; set; }
    }
}
