//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebKullanicilari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebKullanicilari()
        {
            this.WebKullaniciYetkileri = new HashSet<WebKullaniciYetkileri>();
        }
    
        public int id { get; set; }
        public int Cariid { get; set; }
        public string WebKullaniciNo { get; set; }
        public string WebKullaniciSifre { get; set; }
        public string WebKullaniciRoles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebKullaniciYetkileri> WebKullaniciYetkileri { get; set; }
    }
}
